# Generated by Django 5.0.6 on 2024-06-28 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('contact', models.CharField(max_length=100, verbose_name='phone number')),
                ('time', models.TimeField()),
                ('count', models.IntegerField()),
                ('notes', models.TextField(blank=True, max_length=1000)),
            ],
        ),
    ]
